import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const [template, rawCss, hero, previewTemplate, manifestText] = await Promise.all([
  readFile(join(root, "src", "index.template.js"), "utf8"),
  readFile(join(root, "src", "theme.css"), "utf8"),
  readFile(join(root, "assets", "shinobu-hero-safe-landscape.webp")),
  readFile(join(root, "preview", "template.html"), "utf8"),
  readFile(join(root, "manifest.json"), "utf8"),
]);

const manifest = JSON.parse(manifestText);
if (!template.includes("__THEME_CSS_JSON__")) {
  throw new Error("index template is missing __THEME_CSS_JSON__");
}
if (!rawCss.includes("__SHINOBU_HERO_DATA_URI__")) {
  throw new Error("theme CSS is missing __SHINOBU_HERO_DATA_URI__");
}

const heroDataUri = `data:image/webp;base64,${hero.toString("base64")}`;
const css = rawCss.replaceAll("__SHINOBU_HERO_DATA_URI__", heroDataUri);
const entry =
  `/* ${manifest.name} v${manifest.version} — generated by scripts/build.mjs */\n` +
  template.replace("__THEME_CSS_JSON__", JSON.stringify(css));

if (entry.includes("__THEME_CSS_JSON__") || entry.includes("__SHINOBU_HERO_DATA_URI__")) {
  throw new Error("generated entry still contains build placeholders");
}

await mkdir(join(root, "dist"), { recursive: true });
await Promise.all([
  writeFile(join(root, "dist", "index.js"), entry, "utf8"),
  writeFile(join(root, "dist", "theme.css"), css, "utf8"),
  writeFile(
    join(root, "preview", "index.html"),
    previewTemplate.replace("__THEME_CSS__", css.replaceAll("</style>", "<\\/style>")),
    "utf8",
  ),
]);

console.log(
  JSON.stringify(
    {
      entryBytes: Buffer.byteLength(entry),
      heroBytes: hero.length,
      themeBytes: Buffer.byteLength(css),
      version: manifest.version,
    },
    null,
    2,
  ),
);
